#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiQuanCafe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CafeInfo")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCafeInfo(CafeInfo instance);
    partial void UpdateCafeInfo(CafeInfo instance);
    partial void DeleteCafeInfo(CafeInfo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuanLiQuanCafe.Properties.Settings.Default.CafeInfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CafeInfo> CafeInfos
		{
			get
			{
				return this.GetTable<CafeInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CafeInfo")]
	public partial class CafeInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _cafeType;
		
		private string _cafeName;
		
		private int _cafePrice;
		
		private int _cafeAmount;
		
		private string _cafeNote;
		
		private string _cafeTaste;
		
		private string _cafeModify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OncafeTypeChanging(string value);
    partial void OncafeTypeChanged();
    partial void OncafeNameChanging(string value);
    partial void OncafeNameChanged();
    partial void OncafePriceChanging(int value);
    partial void OncafePriceChanged();
    partial void OncafeAmountChanging(int value);
    partial void OncafeAmountChanged();
    partial void OncafeNoteChanging(string value);
    partial void OncafeNoteChanged();
    partial void OncafeTasteChanging(string value);
    partial void OncafeTasteChanged();
    partial void OncafeModifyChanging(string value);
    partial void OncafeModifyChanged();
    #endregion
		
		public CafeInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeType", DbType="Char(10)")]
		public string cafeType
		{
			get
			{
				return this._cafeType;
			}
			set
			{
				if ((this._cafeType != value))
				{
					this.OncafeTypeChanging(value);
					this.SendPropertyChanging();
					this._cafeType = value;
					this.SendPropertyChanged("cafeType");
					this.OncafeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cafeName
		{
			get
			{
				return this._cafeName;
			}
			set
			{
				if ((this._cafeName != value))
				{
					this.OncafeNameChanging(value);
					this.SendPropertyChanging();
					this._cafeName = value;
					this.SendPropertyChanged("cafeName");
					this.OncafeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafePrice", DbType="Int NOT NULL")]
		public int cafePrice
		{
		
			get
			{
				return this._cafePrice;
			}
			set
			{
				if ((this._cafePrice != value))
				{
					this.OncafePriceChanging(value);
					this.SendPropertyChanging();
					this._cafePrice = value;
					this.SendPropertyChanged("cafePrice");
					this.OncafePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeAmount", DbType="Int NOT NULL")]
		public int cafeAmount
		{
			get
			{
				return this._cafeAmount;
			}
			set
			{
				if ((this._cafeAmount != value))
				{
					this.OncafeAmountChanging(value);
					this.SendPropertyChanging();
					this._cafeAmount = value;
					this.SendPropertyChanged("cafeAmount");
					this.OncafeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeNote", DbType="NVarChar(MAX)")]
		public string cafeNote
		{
			get
			{
				return this._cafeNote;
			}
			set
			{
				if ((this._cafeNote != value))
				{
					this.OncafeNoteChanging(value);
					this.SendPropertyChanging();
					this._cafeNote = value;
					this.SendPropertyChanged("cafeNote");
					this.OncafeNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeTaste", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string cafeTaste
		{
			get
			{
				return this._cafeTaste;
			}
			set
			{
				if ((this._cafeTaste != value))
				{
					this.OncafeTasteChanging(value);
					this.SendPropertyChanging();
					this._cafeTaste = value;
					this.SendPropertyChanged("cafeTaste");
					this.OncafeTasteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cafeModify", DbType="NVarChar(MAX)")]
		public string cafeModify
		{
			get
			{
				return this._cafeModify;
			}
			set
			{
				if ((this._cafeModify != value))
				{
					this.OncafeModifyChanging(value);
					this.SendPropertyChanging();
					this._cafeModify = value;
					this.SendPropertyChanged("cafeModify");
					this.OncafeModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
